### ISSUE TITLE
Paired END data set

### ISSUE THREAD

**Issue by Papareddy** [ribosomeprofiling/riboflow#14]
Hi, do this riboflow pipeline suitable for paired end data set.

Cheers,
Ranj

**Comment by hakanozadam** [comment]
Hello,

Typically, Ribosome Profiling (Ribo-Seq) data are single end. So we designed this pipeline for single end sequencing data sets. If there are any matched RNA-Seq experiments, that are paired end, then we recommend using the first read. This way, RNA-Seq and ribosome profiling reads are processed similarly.

**Comment by Papareddy** [comment]
Thank you for the response @hakanozadam. yeah probable we will do SE mode. For now i will just use mate R1
