### ISSUE TITLE
Omitting dedup from the pipeline

### ISSUE THREAD

**Issue by imilenkovic** [ribosomeprofiling/riboflow#16]
Hello,

Would it be possible to omit the dedup step from the pipeline? I would like to see how my final result would look like without this filtering step.

Thanks a lot!

**Comment by hakanozadam** [comment]
Hello,

Yes! In the *project.yaml* file, setting
```
deduplicate: false
```
would omit deduplication.

**Comment by imilenkovic** [comment]
Perfect, thanks a lot!
