### ISSUE TITLE
transcriptome question

### ISSUE THREAD

**Issue by jel4h** [ribosomeprofiling/riboflow#21]
I want to use RiboFlow for a species other than human/mouse, so I will need to provide my own transcriptome.   Does the transcriptome need to only have 1 isoform per gene or can RiboFlow handle multiple isoforms per gene?

Thanks!

**Comment by hakanozadam** [comment]
Hello,

RiboFlow only works with any transcriptome reference. However, we strongly recommend working with **only one isoform** for each gene. For example, for the human and mouse isoforms, we picked the principal isoforms.
